# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'monster' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FontAwesome.swift'
  # Pods for monster

  target 'monsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'monsterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
